language: scala
scala:
  - 2.13.1

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier/cache
    - sysconfcpus

install:
  - TRAVIS_NODE_VERSION="10" nvm install node
  - nvm use node
  - node --version
  - npm --version
  - npm install -g elm

before_script:
  - export TZ=Europe/Berlin

script:
  - sbt ++$TRAVIS_SCALA_VERSION ";project root ;make"
