name: Auto approve

on:
  pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-24.04
    steps:
      - uses: hmarr/auto-approve-action@v4.0.0
        if: github.actor == 'eikek-scala-steward'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
